/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedVirtualNumbersRouteImport } from './routes/_authenticated/virtual-numbers'
import { Route as AuthenticatedRewardRouteImport } from './routes/_authenticated/reward'
import { Route as AuthenticatedRentNumberRouteImport } from './routes/_authenticated/rent-number'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedNumberOrdersRouteImport } from './routes/_authenticated/number-orders'
import { Route as AuthenticatedLogHistoryRouteImport } from './routes/_authenticated/log-history'
import { Route as AuthenticatedHistoryRouteImport } from './routes/_authenticated/history'
import { Route as AuthenticatedFundRouteImport } from './routes/_authenticated/fund'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedBuyAccountsRouteImport } from './routes/_authenticated/buy-accounts'
import { Route as AuthenticatedBoostOrdersRouteImport } from './routes/_authenticated/boost-orders'
import { Route as AuthenticatedBoostRouteImport } from './routes/_authenticated/boost'
import { Route as AuthenticatedAlertsRouteImport } from './routes/_authenticated/alerts'
import { Route as AuthenticatedAffiliateRouteImport } from './routes/_authenticated/affiliate'
import { Route as AuthenticatedAdminPricingRouteImport } from './routes/_authenticated/admin.pricing'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedVirtualNumbersRoute =
  AuthenticatedVirtualNumbersRouteImport.update({
    id: '/virtual-numbers',
    path: '/virtual-numbers',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRewardRoute = AuthenticatedRewardRouteImport.update({
  id: '/reward',
  path: '/reward',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRentNumberRoute = AuthenticatedRentNumberRouteImport.update({
  id: '/rent-number',
  path: '/rent-number',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNumberOrdersRoute =
  AuthenticatedNumberOrdersRouteImport.update({
    id: '/number-orders',
    path: '/number-orders',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLogHistoryRoute = AuthenticatedLogHistoryRouteImport.update({
  id: '/log-history',
  path: '/log-history',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHistoryRoute = AuthenticatedHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFundRoute = AuthenticatedFundRouteImport.update({
  id: '/fund',
  path: '/fund',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBuyAccountsRoute =
  AuthenticatedBuyAccountsRouteImport.update({
    id: '/buy-accounts',
    path: '/buy-accounts',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBoostOrdersRoute =
  AuthenticatedBoostOrdersRouteImport.update({
    id: '/boost-orders',
    path: '/boost-orders',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBoostRoute = AuthenticatedBoostRouteImport.update({
  id: '/boost',
  path: '/boost',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAlertsRoute = AuthenticatedAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAffiliateRoute = AuthenticatedAffiliateRouteImport.update({
  id: '/affiliate',
  path: '/affiliate',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminPricingRoute =
  AuthenticatedAdminPricingRouteImport.update({
    id: '/admin/pricing',
    path: '/admin/pricing',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/affiliate': typeof AuthenticatedAffiliateRoute
  '/alerts': typeof AuthenticatedAlertsRoute
  '/boost': typeof AuthenticatedBoostRoute
  '/boost-orders': typeof AuthenticatedBoostOrdersRoute
  '/buy-accounts': typeof AuthenticatedBuyAccountsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/fund': typeof AuthenticatedFundRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/log-history': typeof AuthenticatedLogHistoryRoute
  '/number-orders': typeof AuthenticatedNumberOrdersRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/rent-number': typeof AuthenticatedRentNumberRoute
  '/reward': typeof AuthenticatedRewardRoute
  '/virtual-numbers': typeof AuthenticatedVirtualNumbersRoute
  '/admin/pricing': typeof AuthenticatedAdminPricingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/affiliate': typeof AuthenticatedAffiliateRoute
  '/alerts': typeof AuthenticatedAlertsRoute
  '/boost': typeof AuthenticatedBoostRoute
  '/boost-orders': typeof AuthenticatedBoostOrdersRoute
  '/buy-accounts': typeof AuthenticatedBuyAccountsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/fund': typeof AuthenticatedFundRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/log-history': typeof AuthenticatedLogHistoryRoute
  '/number-orders': typeof AuthenticatedNumberOrdersRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/rent-number': typeof AuthenticatedRentNumberRoute
  '/reward': typeof AuthenticatedRewardRoute
  '/virtual-numbers': typeof AuthenticatedVirtualNumbersRoute
  '/admin/pricing': typeof AuthenticatedAdminPricingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_authenticated/affiliate': typeof AuthenticatedAffiliateRoute
  '/_authenticated/alerts': typeof AuthenticatedAlertsRoute
  '/_authenticated/boost': typeof AuthenticatedBoostRoute
  '/_authenticated/boost-orders': typeof AuthenticatedBoostOrdersRoute
  '/_authenticated/buy-accounts': typeof AuthenticatedBuyAccountsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/fund': typeof AuthenticatedFundRoute
  '/_authenticated/history': typeof AuthenticatedHistoryRoute
  '/_authenticated/log-history': typeof AuthenticatedLogHistoryRoute
  '/_authenticated/number-orders': typeof AuthenticatedNumberOrdersRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/rent-number': typeof AuthenticatedRentNumberRoute
  '/_authenticated/reward': typeof AuthenticatedRewardRoute
  '/_authenticated/virtual-numbers': typeof AuthenticatedVirtualNumbersRoute
  '/_authenticated/admin/pricing': typeof AuthenticatedAdminPricingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/affiliate'
    | '/alerts'
    | '/boost'
    | '/boost-orders'
    | '/buy-accounts'
    | '/dashboard'
    | '/fund'
    | '/history'
    | '/log-history'
    | '/number-orders'
    | '/profile'
    | '/rent-number'
    | '/reward'
    | '/virtual-numbers'
    | '/admin/pricing'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/affiliate'
    | '/alerts'
    | '/boost'
    | '/boost-orders'
    | '/buy-accounts'
    | '/dashboard'
    | '/fund'
    | '/history'
    | '/log-history'
    | '/number-orders'
    | '/profile'
    | '/rent-number'
    | '/reward'
    | '/virtual-numbers'
    | '/admin/pricing'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_authenticated/affiliate'
    | '/_authenticated/alerts'
    | '/_authenticated/boost'
    | '/_authenticated/boost-orders'
    | '/_authenticated/buy-accounts'
    | '/_authenticated/dashboard'
    | '/_authenticated/fund'
    | '/_authenticated/history'
    | '/_authenticated/log-history'
    | '/_authenticated/number-orders'
    | '/_authenticated/profile'
    | '/_authenticated/rent-number'
    | '/_authenticated/reward'
    | '/_authenticated/virtual-numbers'
    | '/_authenticated/admin/pricing'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/virtual-numbers': {
      id: '/_authenticated/virtual-numbers'
      path: '/virtual-numbers'
      fullPath: '/virtual-numbers'
      preLoaderRoute: typeof AuthenticatedVirtualNumbersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reward': {
      id: '/_authenticated/reward'
      path: '/reward'
      fullPath: '/reward'
      preLoaderRoute: typeof AuthenticatedRewardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rent-number': {
      id: '/_authenticated/rent-number'
      path: '/rent-number'
      fullPath: '/rent-number'
      preLoaderRoute: typeof AuthenticatedRentNumberRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/number-orders': {
      id: '/_authenticated/number-orders'
      path: '/number-orders'
      fullPath: '/number-orders'
      preLoaderRoute: typeof AuthenticatedNumberOrdersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/log-history': {
      id: '/_authenticated/log-history'
      path: '/log-history'
      fullPath: '/log-history'
      preLoaderRoute: typeof AuthenticatedLogHistoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/history': {
      id: '/_authenticated/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AuthenticatedHistoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/fund': {
      id: '/_authenticated/fund'
      path: '/fund'
      fullPath: '/fund'
      preLoaderRoute: typeof AuthenticatedFundRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/buy-accounts': {
      id: '/_authenticated/buy-accounts'
      path: '/buy-accounts'
      fullPath: '/buy-accounts'
      preLoaderRoute: typeof AuthenticatedBuyAccountsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/boost-orders': {
      id: '/_authenticated/boost-orders'
      path: '/boost-orders'
      fullPath: '/boost-orders'
      preLoaderRoute: typeof AuthenticatedBoostOrdersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/boost': {
      id: '/_authenticated/boost'
      path: '/boost'
      fullPath: '/boost'
      preLoaderRoute: typeof AuthenticatedBoostRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/alerts': {
      id: '/_authenticated/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AuthenticatedAlertsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/affiliate': {
      id: '/_authenticated/affiliate'
      path: '/affiliate'
      fullPath: '/affiliate'
      preLoaderRoute: typeof AuthenticatedAffiliateRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/pricing': {
      id: '/_authenticated/admin/pricing'
      path: '/admin/pricing'
      fullPath: '/admin/pricing'
      preLoaderRoute: typeof AuthenticatedAdminPricingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAffiliateRoute: typeof AuthenticatedAffiliateRoute
  AuthenticatedAlertsRoute: typeof AuthenticatedAlertsRoute
  AuthenticatedBoostRoute: typeof AuthenticatedBoostRoute
  AuthenticatedBoostOrdersRoute: typeof AuthenticatedBoostOrdersRoute
  AuthenticatedBuyAccountsRoute: typeof AuthenticatedBuyAccountsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedFundRoute: typeof AuthenticatedFundRoute
  AuthenticatedHistoryRoute: typeof AuthenticatedHistoryRoute
  AuthenticatedLogHistoryRoute: typeof AuthenticatedLogHistoryRoute
  AuthenticatedNumberOrdersRoute: typeof AuthenticatedNumberOrdersRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedRentNumberRoute: typeof AuthenticatedRentNumberRoute
  AuthenticatedRewardRoute: typeof AuthenticatedRewardRoute
  AuthenticatedVirtualNumbersRoute: typeof AuthenticatedVirtualNumbersRoute
  AuthenticatedAdminPricingRoute: typeof AuthenticatedAdminPricingRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAffiliateRoute: AuthenticatedAffiliateRoute,
  AuthenticatedAlertsRoute: AuthenticatedAlertsRoute,
  AuthenticatedBoostRoute: AuthenticatedBoostRoute,
  AuthenticatedBoostOrdersRoute: AuthenticatedBoostOrdersRoute,
  AuthenticatedBuyAccountsRoute: AuthenticatedBuyAccountsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedFundRoute: AuthenticatedFundRoute,
  AuthenticatedHistoryRoute: AuthenticatedHistoryRoute,
  AuthenticatedLogHistoryRoute: AuthenticatedLogHistoryRoute,
  AuthenticatedNumberOrdersRoute: AuthenticatedNumberOrdersRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedRentNumberRoute: AuthenticatedRentNumberRoute,
  AuthenticatedRewardRoute: AuthenticatedRewardRoute,
  AuthenticatedVirtualNumbersRoute: AuthenticatedVirtualNumbersRoute,
  AuthenticatedAdminPricingRoute: AuthenticatedAdminPricingRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
